// Generated by https://quicktype.io

export interface ICustomerGeneralInfo {
  name: string;
  username: string;
  mobile: string;
  nationalCode: number;
  roles: string[];
  permissions: string[];
  inqueryNationalInfo: boolean;
}
