// MUI Imports
import type { Theme } from '@mui/material/styles';

// Type Imports
import type { Skin } from '@/layouts/materialize-layout/@core/types';

const colorSchemes = (skin: Skin): Theme['colorSchemes'] => {
  return {
    light: {
      palette: {
        primary: {
          light: 'rgba(22, 115, 255, 1)',
          main: 'rgba(18, 92, 204, 1)',
          dark: 'rgba(17, 86, 191, 1)',
          contrastText: '#FFF',
          lightestOpacity: 'rgba(231, 241, 255, 1)',
          lighterOpacity: 'rgba(183, 212, 255, 1)',
          lightOpacity: 'rgba(22, 115, 255, 1)',
          mainOpacity: 'rgba(18, 92, 204, 1)',
          darkOpacity: 'rgba(17, 86, 191, 1)',
          darkerOpacity: 'rgba(13, 69, 153, 1)',
          darkestOpacity: 'rgba(8, 40, 89, 1)',
        },
        secondary: {
          light: `var(--mui-mainColorChannels-surface3)`,
          main: `var(--mui-mainColorChannels-surface4)`,
          dark: `var(--mui-mainColorChannels-surface5)`,
          contrastText: '#FFF',
          lighterOpacity: 'rgb(var(--mui-palette-secondary-mainChannel) / 0.08)',
          lightOpacity: 'rgb(var(--mui-palette-secondary-mainChannel) / 0.16)',
          mainOpacity: 'rgb(var(--mui-palette-secondary-mainChannel) / 0.24)',
          darkOpacity: 'rgb(var(--mui-palette-secondary-mainChannel) / 0.32)',
          darkerOpacity: 'rgb(var(--mui-palette-secondary-mainChannel) / 0.38)',
        },
        error: {
          main: 'rgba(242, 25, 74, 1)',
          light: 'rgba(246, 101, 134, 1)',
          dark: 'rgba(220, 23, 67, 1)',
          contrastText: '#FFF',
          lightestOpacity: 'rgba(254, 232, 237, 1)',
          lighterOpacity: 'rgba(251, 184, 199, 1)',
          lightOpacity: 'rgba(246, 101, 134, 1)',
          mainOpacity: 'rgba(242, 25, 74, 1)',
          darkOpacity: 'rgba(220, 23, 67, 1)',
          darkerOpacity: 'rgba(172, 18, 53, 1)',
          darkestOpacity: 'rgba(102, 11, 31, 1)',
        },
        warning: {
          main: 'rgba(252, 215, 123, 1)',
          light: 'rgba(255, 249, 235, 1)',
          dark: 'rgba(228, 177, 53, 1)',
          contrastText: '#FFF',
          lightestOpacity: 'rgba(255, 249, 235, 1)',
          lighterOpacity: 'rgba(254, 236, 194, 1)',
          lightOpacity: 'rgba(252, 215, 123, 1)',
          mainOpacity: 'rgba(252, 215, 123, 1)',
          darkOpacity: 'rgba(228, 177, 53, 1)',
          darkerOpacity: 'rgba(178, 138, 41, 1)',
          darkestOpacity: 'rgba(105, 82, 24, 1)',
        },
        info: {
          main: '#26C6F9',
          light: '#51D1FA',
          dark: '#22B3E1',
          contrastText: '#FFF',
          lighterOpacity: 'rgb(var(--mui-palette-info-mainChannel) / 0.08)',
          lightOpacity: 'rgb(var(--mui-palette-info-mainChannel) / 0.16)',
          mainOpacity: 'rgb(var(--mui-palette-info-mainChannel) / 0.24)',
          darkOpacity: 'rgb(var(--mui-palette-info-mainChannel) / 0.32)',
          darkerOpacity: 'rgb(var(--mui-palette-info-mainChannel) / 0.38)',
        },
        success: {
          main: 'rgba(19, 195, 156, 1)',
          light: 'rgba(97, 215, 189, 1)',
          dark: 'rgba(17, 177, 142, 1)',
          contrastText: '#FFF',
          lightestOpacity: 'rgba(231, 249, 245, 1)',
          lighterOpacity: 'rgba(182, 236, 224, 1)',
          lightOpacity: 'rgba(97, 215, 189, 1)',
          mainOpacity: 'rgba(19, 195, 156, 1)',
          darkOpacity: 'rgba(17, 177, 142, 1)',
          darkerOpacity: 'rgba(13, 138, 111, 1)',
          darkestOpacity: 'rgba(8, 82, 66, 1)',
        },
        text: {
          primary: `var(--mui-mainColorChannels-surface5)`,
          secondary: `var(--mui-mainColorChannels-surface4)`,
          disabled: `var(--mui-mainColorChannels-surface4)`,
          primaryChannel: `var(--mui-mainColorChannels-surface5)`,
          secondaryChannel: `var(--mui-mainColorChannels-surface4)`,
        },
        divider: '#E1E1E7',
        dividerChannel: 'var(--mui-mainColorChannels-surface3)',
        background: {
          default: skin === 'bordered' ? '#FFFFFF' : 'var(--mui-mainColorChannels-surface2)',
          paper: '#FFFFFF',
          paperChannel: '255 255 255',
        },
        action: {
          active: `var(--mui-mainColorChannels-surface3)`,
          hover: `var(--mui-mainColorChannels-surface3)`,
          selected: `var(--mui-mainColorChannels-surface2)`,
          disabled: `var(--mui-mainColorChannels-surface2)`,
          disabledBackground: `var(--mui-mainColorChannels-surface2)`,
          focus: `var(--mui-mainColorChannels-surface3)`,
          focusOpacity: 0.1,
          activeChannel: 'var(--mui-mainColorChannels-surface3)',
          selectedChannel: 'var(--mui-mainColorChannels-surface3)',
        },
        Alert: {
          errorColor: 'var(--mui-palette-error-main)',
          warningColor: 'var(--mui-palette-warning-main)',
          infoColor: 'var(--mui-palette-info-main)',
          successColor: 'var(--mui-palette-success-main)',
          errorStandardBg: 'var(--mui-palette-error-lightOpacity)',
          warningStandardBg: 'var(--mui-palette-warning-lightOpacity)',
          infoStandardBg: 'var(--mui-palette-info-lightOpacity)',
          successStandardBg: 'var(--mui-palette-success-lightOpacity)',
          errorFilledColor: 'var(--mui-palette-error-contrastText)',
          warningFilledColor: 'var(--mui-palette-warning-contrastText)',
          infoFilledColor: 'var(--mui-palette-info-contrastText)',
          successFilledColor: 'var(--mui-palette-success-contrastText)',
          errorFilledBg: 'var(--mui-palette-error-main)',
          warningFilledBg: 'var(--mui-palette-warning-main)',
          infoFilledBg: 'var(--mui-palette-info-main)',
          successFilledBg: 'var(--mui-palette-success-main)',
        },
        Avatar: {
          defaultBg: '#F0EFF0',
        },
        Chip: {
          defaultBorder: 'var(--mui-palette-divider)',
        },
        FilledInput: {
          bg: '#000',
          hoverBg: '#000',
          disabledBg: '#000',
        },
        LinearProgress: {
          primaryBg: 'var(--mui-palette-primary-lightOpacity)',
          secondaryBg: 'var(--mui-palette-secondary-lightOpacity)',
          errorBg: 'var(--mui-palette-error-lightOpacity)',
          warningBg: 'var(--mui-palette-warning-lightOpacity)',
          infoBg: 'var(--mui-palette-info-lightOpacity)',
          successBg: 'var(--mui-palette-success-lightOpacity)',
        },
        SnackbarContent: {
          bg: '#282A42',
          color: 'var(--mui-palette-background-paper)',
        },
        Switch: {
          defaultColor: 'var(--mui-palette-common-white)',
          defaultDisabledColor: 'var(--mui-palette-common-white)',
          primaryDisabledColor: 'var(--mui-palette-common-white)',
          secondaryDisabledColor: 'var(--mui-palette-common-white)',
          errorDisabledColor: 'var(--mui-palette-common-white)',
          warningDisabledColor: 'var(--mui-palette-common-white)',
          infoDisabledColor: 'var(--mui-palette-common-white)',
          successDisabledColor: 'var(--mui-palette-common-white)',
        },
        Tooltip: {
          bg: '#282A42',
        },
        TableCell: {
          border: 'var(--mui-palette-divider)',
        },
        customColors: {
          bodyBg: '#F7F7F7',
          chatBg: '#F7F6FA',
          greyLightBg: '#FAFAFA',
          inputBorder: 'var(--mui-mainColorChannels-surface3)',
          tableHeaderBg: '#F5F5F7',
          tooltipText: '#FFFFFF',
          trackBg: '#F5F5F8',
          menuItemColor: `#B7D4FF`,
        },
      },
    },
    dark: {
      palette: {
        primary: {
          light: 'rgba(22, 115, 255, 1)',
          main: 'rgba(18, 92, 204, 1)',
          dark: 'rgba(17, 86, 191, 1)',
          lightestOpacity: 'rgba(231, 241, 255, 1)',
          lighterOpacity: 'rgba(183, 212, 255, 1)',
          lightOpacity: 'rgba(22, 115, 255, 1)',
          mainOpacity: 'rgba(18, 92, 204, 1)',
          darkOpacity: 'rgba(17, 86, 191, 1)',
          darkerOpacity: 'rgba(13, 69, 153, 1)',
          darkestOpacity: 'rgba(8, 40, 89, 1)',
        },
        secondary: {
          main: '#6D788D',
          light: '#8A93A4',
          dark: '#626C7F',
          contrastText: '#FFF',
          lighterOpacity: 'rgb(var(--mui-palette-secondary-mainChannel) / 0.08)',
          lightOpacity: 'rgb(var(--mui-palette-secondary-mainChannel) / 0.16)',
          mainOpacity: 'rgb(var(--mui-palette-secondary-mainChannel) / 0.24)',
          darkOpacity: 'rgb(var(--mui-palette-secondary-mainChannel) / 0.32)',
          darkerOpacity: 'rgb(var(--mui-palette-secondary-mainChannel) / 0.38)',
        },
        error: {
          main: 'rgba(242, 25, 74, 1)',
          light: 'rgba(246, 101, 134, 1)',
          dark: 'rgba(220, 23, 67, 1)',
          contrastText: '#FFF',
          lightestOpacity: 'rgba(254, 232, 237, 1)',
          lighterOpacity: 'rgba(251, 184, 199, 1)',
          lightOpacity: 'rgba(246, 101, 134, 1)',
          mainOpacity: 'rgba(242, 25, 74, 1)',
          darkOpacity: 'rgba(220, 23, 67, 1)',
          darkerOpacity: 'rgba(172, 18, 53, 1)',
          darkestOpacity: 'rgba(102, 11, 31, 1)',
        },
        warning: {
          main: 'rgba(252, 215, 123, 1)',
          light: 'rgba(255, 249, 235, 1)',
          dark: 'rgba(228, 177, 53, 1)',
          contrastText: '#FFF',
          lightestOpacity: 'rgba(255, 249, 235, 1)',
          lighterOpacity: 'rgba(254, 236, 194, 1)',
          lightOpacity: 'rgba(252, 215, 123, 1)',
          mainOpacity: 'rgba(252, 215, 123, 1)',
          darkOpacity: 'rgba(228, 177, 53, 1)',
          darkerOpacity: 'rgba(178, 138, 41, 1)',
          darkestOpacity: 'rgba(105, 82, 24, 1)',
        },
        info: {
          main: '#26C6F9',
          light: '#51D1FA',
          dark: '#22B3E1',
          contrastText: '#FFF',
          lighterOpacity: 'rgb(var(--mui-palette-info-mainChannel) / 0.08)',
          lightOpacity: 'rgb(var(--mui-palette-info-mainChannel) / 0.16)',
          mainOpacity: 'rgb(var(--mui-palette-info-mainChannel) / 0.24)',
          darkOpacity: 'rgb(var(--mui-palette-info-mainChannel) / 0.32)',
          darkerOpacity: 'rgb(var(--mui-palette-info-mainChannel) / 0.38)',
        },
        success: {
          main: 'rgba(19, 195, 156, 1)',
          light: 'rgba(97, 215, 189, 1)',
          dark: 'rgba(17, 177, 142, 1)',
          contrastText: '#FFF',
          lightestOpacity: 'rgba(231, 249, 245, 1)',
          lighterOpacity: 'rgba(182, 236, 224, 1)',
          lightOpacity: 'rgba(97, 215, 189, 1)',
          mainOpacity: 'rgba(19, 195, 156, 1)',
          darkOpacity: 'rgba(17, 177, 142, 1)',
          darkerOpacity: 'rgba(13, 138, 111, 1)',
          darkestOpacity: 'rgba(8, 82, 66, 1)',
        },
        text: {
          primary: `var(--mui-mainColorChannels-surface3)`,
          secondary: `var(--mui-mainColorChannels-surface2)`,
          disabled: `var(--mui-mainColorChannels-surface1)`,
          primaryChannel: `var(--mui-mainColorChannels-surface3)`,
          secondaryChannel: `var(--mui-mainColorChannels-surface2)`,
        },
        divider: `rgb(var(--mui-mainColorChannels-dark) / 0.12)`,
        dividerChannel: 'var(--mui-mainColorChannels-dark)',
        background: {
          default: skin === 'bordered' ? '#30334E' : '#282A42',
          paper: '#30334E',
          paperChannel: '48 51 78',
        },
        action: {
          active: `rgb(var(--mui-mainColorChannels-light) / 0.6)`,
          hover: `rgb(var(--mui-mainColorChannels-light) / 0.06)`,
          selected: `rgb(var(--mui-mainColorChannels-light) / 0.08)`,
          disabled: `rgb(var(--mui-mainColorChannels-light) / 0.3)`,
          disabledBackground: `rgb(var(--mui-mainColorChannels-light) / 0.16)`,
          focus: `rgb(var(--mui-mainColorChannels-light) / 0.1)`,
          focusOpacity: 0.1,
          activeChannel: 'var(--mui-mainColorChannels-light)',
          selectedChannel: 'var(--mui-mainColorChannels-light)',
        },
        Alert: {
          errorColor: 'var(--mui-palette-error-main)',
          warningColor: 'var(--mui-palette-warning-main)',
          infoColor: 'var(--mui-palette-info-main)',
          successColor: 'var(--mui-palette-success-main)',
          errorStandardBg: 'var(--mui-palette-error-lightOpacity)',
          warningStandardBg: 'var(--mui-palette-warning-lightOpacity)',
          infoStandardBg: 'var(--mui-palette-info-lightOpacity)',
          successStandardBg: 'var(--mui-palette-success-lightOpacity)',
          errorFilledColor: 'var(--mui-palette-error-contrastText)',
          warningFilledColor: 'var(--mui-palette-warning-contrastText)',
          infoFilledColor: 'var(--mui-palette-info-contrastText)',
          successFilledColor: 'var(--mui-palette-success-contrastText)',
          errorFilledBg: 'var(--mui-palette-error-main)',
          warningFilledBg: 'var(--mui-palette-warning-main)',
          infoFilledBg: 'var(--mui-palette-info-main)',
          successFilledBg: 'var(--mui-palette-success-main)',
        },
        Avatar: {
          defaultBg: '#383B55',
        },
        Chip: {
          defaultBorder: 'var(--mui-palette-divider)',
        },
        FilledInput: {
          bg: 'var(--mui-palette-action-hover)',
          hoverBg: 'var(--mui-palette-action-selected)',
          disabledBg: 'var(--mui-palette-action-hover)',
        },
        LinearProgress: {
          primaryBg: 'var(--mui-palette-primary-lightOpacity)',
          secondaryBg: 'var(--mui-palette-secondary-lightOpacity)',
          errorBg: 'var(--mui-palette-error-lightOpacity)',
          warningBg: 'var(--mui-palette-warning-lightOpacity)',
          infoBg: 'var(--mui-palette-info-lightOpacity)',
          successBg: 'var(--mui-palette-success-lightOpacity)',
        },
        SnackbarContent: {
          bg: '#F5F5F5',
          color: 'var(--mui-palette-background-paper)',
        },
        Switch: {
          defaultColor: 'var(--mui-palette-common-white)',
          defaultDisabledColor: 'var(--mui-palette-common-white)',
          primaryDisabledColor: 'var(--mui-palette-common-white)',
          secondaryDisabledColor: 'var(--mui-palette-common-white)',
          errorDisabledColor: 'var(--mui-palette-common-white)',
          warningDisabledColor: 'var(--mui-palette-common-white)',
          infoDisabledColor: 'var(--mui-palette-common-white)',
          successDisabledColor: 'var(--mui-palette-common-white)',
        },
        Tooltip: {
          bg: '#F5F5F5',
        },
        TableCell: {
          border: 'var(--mui-palette-divider)',
        },
        customColors: {
          bodyBg: '#282A42',
          chatBg: '#343752',
          greyLightBg: '#333851',
          inputBorder: `rgb(var(--mui-mainColorChannels-dark) / 0.22)`,
          tableHeaderBg: '#3A3E5B',
          tooltipText: '#30334E',
          trackBg: '#3C3F59',
          menuItemColor: `#B7D4FF`,
        },
      },
    },
  } as Theme['colorSchemes'];
};

export default colorSchemes;
